import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import Head from 'next/head';

const inter = Inter({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>
        <title>{ metadata?.title }</title>
        <meta name="description" content={description} />
        <meta name="og:title" content={title} />
        <meta name="og:description" content={pageDescription} />

        {
        imageFullUrl && (
          <meta name="og:image" content={imageFullUrl} />
        )
      }

      </Head> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
